import {StyleSheet} from 'react-native';
import {Size} from './Size';

export const Font = StyleSheet.create({
  title: {
    fontFamily: 'NotoSansKR-Bold',
    fontSize: Size.width(28),
    fontWeight: 'bold',
    fontStyle: 'normal',
    letterSpacing: -0.56,
    textAlign: 'left',
  },
  head: {
    fontFamily: 'NotoSansKR-Regular',
    fontSize: Size.width(28),
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.56,
    textAlign: 'left',
  },
  body1: {
    fontFamily: 'NotoSansKR-Regular',
    fontSize: Size.width(16),
    fontWeight: 'normal',
    fontStyle: 'normal',
    textAlign: 'left',
  },
  body2: {
    fontFamily: 'NotoSansKR-Bold',
    fontSize: Size.width(16),
    fontWeight: 'bold',
    fontStyle: 'normal',
    textAlign: 'left',
    lineHeight: Size.width(22),
  },
  subtext: {
    fontFamily: 'NotoSansKR-Bold',
    fontSize: Size.width(14),
    fontWeight: 'bold',
    fontStyle: 'normal',
    letterSpacing: -0.14,
    textAlign: 'left',
  },
  subtext1: {
    fontFamily: 'NotoSansKR-Regular',
    fontSize: Size.width(14),
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.14,
    textAlign: 'left',
  },
  subtext2: {
    fontFamily: 'NotoSansKR-Bold',
    fontSize: Size.width(12),
    fontWeight: 'bold',
    fontStyle: 'normal',
    textAlign: 'left',
  },
  subtext3: {
    fontFamily: 'NotoSansKR-Regular',
    fontSize: Size.width(12),
    fontWeight: 'normal',
    fontStyle: 'normal',
    textAlign: 'left',
  },
  subtext4: {
    fontFamily: 'NotoSansKR-Regular',
    fontSize: Size.width(14),
    fontWeight: 'normal',
    fontStyle: 'normal',
    letterSpacing: -0.2,
    textAlign: 'left',
  },
  smalltext: {
    fontFamily: 'NotoSansKR-Regular',
    fontSize: Size.width(10),
    fontWeight: 'normal',
    fontStyle: 'normal',
    textAlign: 'left',
  },
  small_bold_text: {
    fontFamily: 'NotoSansKR-Bold',
    fontSize: Size.width(10),
    fontWeight: 'bold',
    fontStyle: 'normal',
    textAlign: 'left',
  },
  textinputbold: {
    fontFamily: 'NotoSansKR-Bold',
    fontSize: Size.width(16),
    fontWeight: 'bold',
    fontStyle: 'normal',
    textAlign: 'left',
  },
  mini_text: {
    fontFamily: 'NotoSansKR-Bold',
    fontSize: Size.width(8),
    fontWeight: 'bold',
    fontStyle: 'normal',
    textAlign: 'left',
  },
});
